apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DB_USER: "admin"
  DB_NAME: "notes_db"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  PORT: "5000"
  INGRESS: "http://localhost:8081"